# Title: Anonymize your Data Set with the R Package sdcMicro


## Audience:

The participants may come from any field of data science and statistics, but typically the audience consists of participants who work with any kind of personal data or who already got in touch with confidentialy and data privacy or who have a demand on data from institutions or data collectors but could not receive the data in full detail because of laws on privacy.  

<!-- ideally -->
<!-- The audience is expected to have sound knowledge on the application of data manipulation steps in base R as well as basic statistical knowledge, e.g., mean, median, variance, correlation, regression. -->

## Instructors:

- Alexander Kowarik (https://github.com/alexkowa, https://www.linkedin.com/in/alexander-kowarik-37004ab/, https://twitter.com/alexkvienna) is head of the methods unit at Staitstics Austria, the national statistical institute of Austria.   
- Matthias Templ (https://github.com/matthias-da, https://www.zhaw.ch/de/ueber-uns/person/teml/) is lecturer and researcher at the Zurich University of Applied Sciences. 

Both are authors of the [sdcMicro](https://cran.r-project.org/package=sdcMicro) R package and have experience to train R and statistical disclosure control methods on a university level as well as a professional level,e.g., in the ‘European Statistical Training Programme’. 

## Domain and points of appeal:

New technologies and research in the field of machine learning and deep learning methods and new ways of accessing, integrating and analyzing sensitive personal data increase the demand for solutions to be able to respect laws on data privacy and confidentialiy. 

Fields of applications include official statistics and social sciences, financial transactions, social network activities, location trajectories, CRM, insurance data and medical records. 
New data protection regulations, that especially include high penalities for violating privacy, put the topic of statistical disclosure control in focus.

Pseudo-anonymization (with salting and hasing) should not be mixed with anonymization, because it does not prevent the successful re-identification of persons, which is typically done by a combination of attributes. Statistical disclosure control includes the measurement of the re-identification risk of persons in a data set, the anonymization of data and the measurement of the information loss after anonymization. 
After anonymization the data include no link to persons, and thus all the rules on privacy do no longer apply. 

<!-- # Points of appeal:  -->

<!-- ~75 words, describing what makes the proposed tutorial appealing to either audience from a broad range of backgrounds. If the tutorial content draws on examples from multiple fields/disciplines, the fields are identified and the tutorial is described in a way that is appealing to audience from those and related disciplines. -->



## Learning objectives:

<!-- The aim is to get a deep understanding of the classes and methods of the sdcMicro packages.  -->
<!-- Various popular methods are first explained and applied on complex data sets. -->
<!-- Afterwards we step back to discuss the whole workflow when anonymizing a complex data set. Interactively, together with the audience, we will anonymize one data set and show the results on risk and utility.   -->

The lessons learnt will include 

- the knowledge of the basic methods on estimating the re-identification risk of persons ($k$-anonymity, suda, individual and global risk), data anonymization (recoding, local suppression, pram, noise, aggregation) and estimating the data utility after anonymization;
- the basic understanding of a data- and use-case-driven anonymisation; 
- a deep understanding of the classes and methods of the sdcMicro packages. 

<!-- 100 – 200 words, describing the specific concepts and skills the audience can expect to have learned by attending the tutorial. Be sure to specify each learning objective succinctly. A well-drafted proposal would probably have 3-5 well-stated learning objectives. -->

## Computing requirements:

Please install the [sdcMicro](https://cran.r-project.org/package=sdcMicro) package prior to the tutorial. 
There is no other special software requirements needed. 

<!-- ~50 words, describing the minimum hardware configuration and software attendees should bring to the tutorial to benefit from the hands-on exercises given during the tutorial. -->

## Teaching assistant: 

We briefly explain the most popular methods on risk estimation, anonymisation and measurement of data utility. After each method explained, we demonstrate a method via a code example on a complex data set. 
Afterwards we step back to discuss the whole workflow when anonymizing a complex data set. In the end of the tutorial there is time for hands-on in an interactive manner and structured by the course leaders. Question can be raised anytime and especially in the last session on the interactive part we motivate the course participants for discussions and hands-on code.

<!-- Das verstehe ich nicht recht gut: erster Teil (unten) ist doch fuer das Staff dort und der lesson plan aber wiederum fuer die participants? -->
<!-- will you be able to identify one-two individuals who can serve as teaching assistants? Will you need the conference committee to identify volunteers who can serve as teaching assistants? What subject matter expertise should such an individual have to help with any difficulties that the attendees might face in running the code examples being demonstrated? Lesson plan: ~150 words, describing via a bulleted list, a sketch of the sequence of activities (theory/domain explanation, demonstration of code, hands-on work time, formal/informal Q+A, etc.) that the instructor expects to follow for delivering the learning experience to attendees. -->

## Expected level of audience’s R background:

The audience is expected to have sound knowledge in data manipulation steps in base R as well as basic statistical knowledge, e.g., mean, median, variance, correlation, regression.

## Further readings and documents:


- sdcMicro devolopment [github](https://github.com/sdcTools/sdcMicro)
- sdcMicro stable CRAN version [CRAN](https://cran.r-project.org/web/packages/sdcMicro/index.html)
- Publication sdcMicro: [Journal of Statistical Software: sdcMicro](https://www.jstatsoft.org/article/view/v067i04)
- Publication of a [sdc app](https://www.mdpi.com/1999-4893/12/9/191/htm)
- Book on SDC in [Springer](https://www.springer.com/de/book/9783319502700)

Prominent distributors of sdcMicro:

- [International Household Survey Network](http://www.ihsn.org/software/disclosure-control-toolbox)
- [World Bank Group](http://surveys.worldbank.org/sdcmicro)


<!-- ~50 words, a designation of beginner, intermediate, or advanced, and a short description of expected R-related skills. Other considerations:  ~ 100 words, describing any other constraints/needs the instructor might have that are relevant in delivering the learning experience to the attendees. If there are additional resources (available online) that the instructor things can help the audience to continue their learning beyond the tutorial, they can be included here, too. -->

<!-- (Call: https://user2020.r-project.org/news/2019/09/28/call-for-tutorials/) -->